# Generated by Django 5.2 on 2025-04-22 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chair',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='university',
        ),
        migrations.AddField(
            model_name='chair',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.faculty'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.university'),
        ),
    ]
